[project]
name = "bookmarko"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mysqlclient>=2.2.7",
    "pip-audit>=2.10.0",
    "sqlalchemy-fulltext-search>=0.3.0",
]
